//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp_HiepBui
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.ORDERS = new HashSet<ORDER>();
        }
    
        public string IDEmp { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Status_emp { get; set; }
        public string IDKindEmp { get; set; }
        public string IDGroup { get; set; }
        public string IDTypeUser { get; set; }
        public string IDStore { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual GROUP_OF_EMPLOYEE GROUP_OF_EMPLOYEE { get; set; }
        public virtual KIND_OF_EMPLOYEE KIND_OF_EMPLOYEE { get; set; }
        public virtual STORE STORE { get; set; }
        public virtual TYPE_OF_USER TYPE_OF_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERS { get; set; }
        public virtual WORKINGTIME WORKINGTIME { get; set; }
    }
}
