//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp_HiepBui
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM()
        {
            this.ITEM_IN_ORDER = new HashSet<ITEM_IN_ORDER>();
        }
    
        public string IDItem { get; set; }
        public string NameItem { get; set; }
        public int Price { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string IDType { get; set; }
        public string IDStore { get; set; }
        public string IDSupplier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_IN_ORDER> ITEM_IN_ORDER { get; set; }
        public virtual STORE STORE { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        public virtual TYPE_OF_ITEM TYPE_OF_ITEM { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
