//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp_HiepBui
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Info_Of_Customers
    {
        public string IDCustomer { get; set; }
        public string Name_of_Customer { get; set; }
        public string Phone { get; set; }
        public string OpeningDate { get; set; }
        public string Latest_transaction { get; set; }
        public string NameTypeOfCustomer { get; set; }
        public int AccumulatedPoint { get; set; }
    }
}
