//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp_HiepBui
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Order_Detail
    {
        public string ID_Order { get; set; }
        public string Name_customer { get; set; }
        public int Total_price { get; set; }
        public System.DateTime Day_transaction { get; set; }
    }
}
