//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp_HiepBui
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Status_Of_WareHouse
    {
        public string IDItem { get; set; }
        public string NameItem { get; set; }
        public int Price { get; set; }
        public string Type { get; set; }
        public string NameOfSupplier { get; set; }
        public int NumberOfItem { get; set; }
        public string ProductionDate { get; set; }
        public string ExpirationDate { get; set; }
    }
}
