//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp_HiepBui
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Working_time
    {
        public string IDEmp { get; set; }
        public string Name { get; set; }
        public string Status_Employee { get; set; }
        public string Position { get; set; }
        public string Kind_of_Employee { get; set; }
        public int TotalTime { get; set; }
    }
}
